# Originally Travis CI setup for fpvFoam
# Ref: https://github.com/turbinesFoam/turbinesFoam
# Migrate to Github Actions

name: Built fpvFoam

# Triggered when code is pushed to any branch in the repository
on: [push, pull_request]

# Jobs
jobs:
  fpvFoam-build:
    
    runs-on: ubuntu-latest
    container:
      image: ubuntu:trusty 
      options: "--entrypoint /bin/bash"
      
      env:
        OF_VERS: 231

    steps:
      - uses: actions/checkout@v2
      - name: Install OpenFOAM
        run: |
          pwd

          # Install and change shell to bash
          sudo apt-get install -y bash
          sudo rm /bin/sh
          sudo ln -s /bin/bash /bin/sh
          # Add OpenFOAM binary release repository
          sudo apt-get install -y wget software-properties-common
          sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
          sudo add-apt-repository http://dl.openfoam.org/ubuntu
          sudo apt-get update -qq
          # Install prequisites
          sudo apt-get install -y build-essential cmake flex bison zlib1g-dev qt4-dev-tools libqt4-dev libqtwebkit-dev gnuplot 
          sudo apt-get install -y libreadline-dev libncurses-dev libxt-dev libopenmpi-dev openmpi-bin libboost-system-dev libboost-thread-dev libgmp-dev libmpfr-dev
          # Install OF231
          sudo apt-get install  -y openfoam${OF_VERS}
          #wget --no-check-certificate https://raw.githubusercontent.com/TimoLin/OpenFOAM-doc/master/openfoam${OF_VERS}_0-1_amd64.deb
          #sudo chmod 777 openfoam${OF_VERS}_0-1_amd64.deb
          #sudo apt-get -f install ./openfoam${OF_VERS}_0-1_amd64.deb

      - name: Build fpvFoam
        run: |
          source /opt/openfoam${OF_VERS}/etc/bashrc
          export LIB_FPV_SRC=$HOME/fpvFoam/src/
          ./Allwmake

      - name: Fetch fpvFoamCases
        run: |
          source /opt/openfoam${OF_VERS}/etc/bashrc
          cd ../
          git clone https://github.com/TimoLin/foamTestCases.git
          cd foamTestCases

      - name: Test fpvFoam
        run: |
          cd fpvFoam
          ./Allrun
          tail log.fpvFoam
